GET http://localhost:3001/api/menus/

### checks unknown end points
GET http://localhost:3001/api/menus/12312321

### checks for single menu
GET http://localhost:3001/api/menus/64a355e78dceb955b68075e2