export const dairyItems = {
  milk: "dairy",
  "whole milk": "dairy",
  "2% milk": "dairy",
  "1% milk": "dairy",
  "two percent milk": "dairy",
  "one percent milk": "dairy",
  "skim milk": "dairy",
  "sour cream": "dairy",
  "greek yogurt": "dairy",
  "cottage cheese": "dairy",
  butter: "dairy",
  yogurt: "dairy",
  cream: "dairy",
  "whipped cream": "dairy",
  "half and half": "dairy",
  "heavy cream": "dairy",
  "almond milk": "dairy",
  "cashew milk": "dairy",
  "oat milk": "dairy",
  "soy milk": "dairy",
  "rice milk": "dairy",
  "chocolate milk": "dairy",
  "goat milk": "dairy",
  "sheep milk": "dairy",
  "lactose-free milk": "dairy",
  "whipped butter": "dairy",
  "unsalted butter": "dairy",
  "salted butter": "dairy",
  "margarine spread": "dairy",
  "cream cheese": "dairy",
  egg: "dairy",
  eggs: "dairy",
  "egg whites": "dairy",
  "egg yolks": "dairy",
};
