export const deliItems = {
  ham: "deli",
  turkey: "deli",
  "roast beef": "deli",
  salami: "deli",
  bologna: "deli",
  pastrami: "deli",
  "roasted chicken breast": "deli",
  prosciutto: "deli",
  pepperoni: "deli",
  "corned beef": "deli",
  capicola: "deli",
  liverwurst: "deli",
  "genoa salami": "deli",
  soppressata: "deli",
  "black forest ham": "deli",
  "smoked ham": "deli",
  "honey ham": "deli",
  "turkey breast": "deli",
  "smoked turkey": "deli",
  "cajun turkey": "deli",
  "buffalo chicken": "deli",
  "provolone cheese": "deli",
  parmesan: "deli",
  "cheddar cheese": "deli",
  "swiss cheese": "deli",
  "american cheese": "deli",
  "mozzarella cheese": "deli",
  "pepper jack cheese": "deli",
  "muenster cheese": "deli",
  "colby jack cheese": "deli",
  "gouda cheese": "deli",
  "feta cheese": "deli",
  "blue cheese": "deli",
  "gorgonzola cheese": "deli",
  "asiago cheese": "deli",
  "havarti cheese": "deli",
  "goat cheese": "deli",
  "cream cheese": "deli",
  "pimento cheese": "deli",
  "olive loaf": "deli",
  "head cheese": "deli",
  "liver pate": "deli",
  "smoked salmon": "deli",
  "kielbasa sausage": "deli",
  "hot dogs": "deli",
};
