export const meatDepartmentItems = {
  beef: "meat",
  chicken: "meat",
  pork: "meat",
  lamb: "meat",
  veal: "meat",
  "ground beef": "meat",
  "ground chicken": "meat",
  "ground pork": "meat",
  "ground lamb": "meat",
  "ground veal": "meat",
  steak: "meat",
  bacon: "meat",
  sausage: "meat",
  "whole turkey": "meat",
  "corned beef": "meat",
  "chicken breast": "meat",
  "chicken thighs": "meat",
  "chicken wings": "meat",
  "chicken drumsticks": "meat",
  "whole chicken": "meat",
  "ground turkey": "meat",
  "turkey bacon": "meat",
  "turkey sausage": "meat",
  "pork chops": "meat",
  "pork tenderloin": "meat",
  "pork ribs": "meat",
  "pork baby back ribs": "meat",
  "pork shoulder": "meat",
  "lamb chops": "meat",
  "lamb leg": "meat",
  "lamb shank": "meat",
  "lamb ribs": "meat",
  "veal cutlets": "meat",
  "veal chops": "meat",
  "veal roast": "meat",
  shrimp: "seafood",
  salmon: "seafood",
  tuna: "seafood",
  cod: "seafood",
  crab: "seafood",
  lobster: "seafood",
  scallops: "seafood",
  mussels: "seafood",
  clams: "seafood",
  oysters: "seafood",
  squid: "seafood",
};
