export const meatDepartmentItems = {
  beef: "meat",
  chicken: "meat",
  pork: "meat",
  lamb: "meat",
  veal: "meat",
  "ground beef": "meat",
  "ground chicken": "meat",
  "ground pork": "meat",
  "ground lamb": "meat",
  "ground veal": "meat",
  steak: "meat",
  bacon: "meat",
  sausage: "meat",
  "whole turkey": "meat",
  "corned beef": "meat",
  "chicken breast": "meat",
  "boneless chicken breast": "meat",
  "boneless chicken breasts": "meat",
  "chicken thighs": "meat",
  "chicken wings": "meat",
  "chicken drumsticks": "meat",
  "whole chicken": "meat",
  "ground turkey": "meat",
  "turkey bacon": "meat",
  "turkey sausage": "meat",
  "pork chops": "meat",
  "pork tenderloin": "meat",
  "pork ribs": "meat",
  "pork baby back ribs": "meat",
  "pork shoulder": "meat",
  "pork butt": "meat",
  "boneless pork shoulder": "meat",
  "lamb chops": "meat",
  "lamb leg": "meat",
  "lamb shank": "meat",
  "lamb ribs": "meat",
  "veal cutlets": "meat",
  "veal chops": "meat",
  "veal roast": "meat",
  "andouille sausage": "meat",
  shrimp: "meat",
  salmon: "meat",
  tuna: "meat",
  cod: "meat",
  crab: "meat",
  lobster: "meat",
  scallops: "meat",
  mussels: "meat",
  clams: "meat",
  oysters: "meat",
  squid: "meat",
};
