export const middleAislesItems = {
  "white bread": "middle aisles",
  "slices of white bread": "middle aisles",
  "wheat bread": "middle aisles",
  "multigrain bread": "middle aisles",
  "rye bread": "middle aisles",
  "sourdough bread": "middle aisles",
  "hamburger buns": "middle aisles",
  "hot dog buns": "middle aisles",
  tortillas: "middle aisles",
  "corn tortillas": "middle aisles",
  "12 inch tortillas": "middle aisles",
  "4 inch tortillas": "middle aisles",
  "6 inch tortillas": "middle aisles",
  horseradish: "middle aisles",
  "creamy horseradish": "middle aisles",
  mayonnaise: "middle aisles",
  mayo: "middle aisles",
  mustard: "middle aisles",
  "dijon mustard": "middle aisles",
  "spicy mustard": "middle aisles",
  ketchup: "middle aisles",
  relish: "middle aisles",
  sauerkraut: "middle aisles",
  "sweet relish": "middle aisles",
  "pickle relish": "middle aisles",
  pickles: "middle aisles",
  "worcestershire sauce": "middle aisles",
  worcestershire: "middle aisles",
  "franks hot sauce": "middle aisles",
  tabasco: "middle aisles",
  cholula: "middle aisles",
  olives: "middle aisles",
  "kalamata olives": "middle aisles",
  "black olives": "middle aisles",
  "stuffed olives": "middle aisles",
  "green olives": "middle aisles",
  "martini olives": "middle aisles",
  "hot sauce": "middle aisles",
  "BBQ sauce": "middle aisles",
  "honey mustard": "middle aisles",
  "ranch dressing": "middle aisles",
  "caesar dressing": "middle aisles",
  "vinaigrette dressing": "middle aisles",
  "canned tomatoes": "middle aisles",
  "canned crushed tomatoes": "middle aisles",
  "tomato puree": "middle aisles",
  "tomato paste": "middle aisles",
  "whole cannoned tomatoes": "middle aisles",
  "san marzano tomatoes": "middle aisles",
  "diced cannoned tomatoes": "middle aisles",
  "canned beans": "middle aisles",
  "canned garbanzo beans": "middle aisles",
  "canned chickpeas": "middle aisles",
  "canned artichoke hearts": "middle aisles",
  "canned corn": "middle aisles",
  "canned peas": "middle aisles",
  "canned carrots": "middle aisles",
  "canned green beans": "middle aisles",
  "canned spinach": "middle aisles",
  "canned mushrooms": "middle aisles",
  "canned olives": "middle aisles",
  "canned tuna": "middle aisles",
  "canned salmon": "middle aisles",
  "canned sardines": "middle aisles",
  "canned chicken": "middle aisles",
  "canned soup": "middle aisles",
  "canned chili": "middle aisles",
  "canned vegetables": "middle aisles",
  "canned fruit": "middle aisles",
  "canned peaches": "middle aisles",
  "canned pineapple": "middle aisles",
  "pineapple juice": "middle aisles",
  "canned water chestnuts": "middle aisles",
  "water chestnuts": "middle aisles",
  "chicken broth": "middle aisles",
  "powdered chicken stock": "middle aisles",
  "powdered chicken stock (optional)": "middle aisles",
  "chicken stock": "middle aisles",
  "beef broth": "middle aisles",
  "beef stock": "middle aisles",
  "vegetable broth": "middle aisles",
  "vegetable stock": "middle aisles",
  "pork broth": "middle aisles",
  "pork stock": "middle aisles",
  "black beans": "middle aisles",
  "kidney beans": "middle aisles",
  "pinto beans": "middle aisles",
  "navy beans": "middle aisles",
  "garbanzo beans": "middle aisles",
  lentils: "middle aisles",
  "split peas": "middle aisles",
  "black-eyed peas": "middle aisles",
  "red beans": "middle aisles",
  "white beans": "middle aisles",
  rice: "middle aisles",
  "uncooked white rice": "middle aisles",
  "uncooked brown rice": "middle aisles",
  "uncooked jasmine rice": "middle aisles",
  "uncooked basmati rice": "middle aisles",
  "uncooked wild rice": "middle aisles",
  "white rice": "middle aisles",
  "brown rice": "middle aisles",
  "jasmine rice": "middle aisles",
  "basmati rice": "middle aisles",
  "wild rice": "middle aisles",
  "arborio rice": "middle aisles",
  "sushi rice": "middle aisles",
  "long grain rice": "middle aisles",
  "short grain rice": "middle aisles",
  "parboiled rice": "middle aisles",
  quinoa: "middle aisles",
  couscous: "middle aisles",
  bulgur: "middle aisles",
  farro: "middle aisles",
  barley: "middle aisles",
  spaghetti: "middle aisles",
  penne: "middle aisles",
  macaroni: "middle aisles",
  fusilli: "middle aisles",
  linguine: "middle aisles",
  fettuccine: "middle aisles",
  rigatoni: "middle aisles",
  farfalle: "middle aisles",
  orzo: "middle aisles",
  lasagna: "middle aisles",
  rotini: "middle aisles",
  cavatappi: "middle aisles",
  tortellini: "middle aisles",
  ravioli: "middle aisles",
  angelHair: "middle aisles",
  vermicelli: "middle aisles",
  manicotti: "middle aisles",
  capellini: "middle aisles",
  ziti: "middle aisles",
  pappardelle: "middle aisles",
  //middle aisles begin
  "soy sauce": "middle aisles",
  "rice vinegar": "middle aisles",
  "sesame oil": "middle aisles",
  "fish sauce": "middle aisles",
  "hoisin sauce": "middle aisles",
  "oyster sauce": "middle aisles",
  "sriracha sauce": "middle aisles",
  "sambal oelek": "middle aisles",
  "sambal paste": "middle aisles",
  "coconut milk": "middle aisles",
  "curry paste": "middle aisles",
  "dried seaweed": "middle aisles",
  "rice noodles": "middle aisles",
  "linguine rice noodles": "middle aisles",
  "large flat rice noodles": "middle aisles",
  "ramen noodles": "middle aisles",
  "miso paste": "middle aisles",
  tofu: "middle aisles",
  "panko breadcrumbs": "middle aisles",
  "sweet chili sauce": "middle aisles",
  "nori sheets": "middle aisles",
  //baking section begin
  flour: "middle aisles",
  sugar: "middle aisles",
  "brown sugar": "middle aisles",
  "powdered sugar": "middle aisles",
  "baking powder": "middle aisles",
  "baking soda": "middle aisles",
  yeast: "middle aisles",
  "cocoa powder": "middle aisles",
  "corn starch": "middle aisles",
  "cake mix": "middle aisles",
  "pancake mix": "middle aisles",
  "bread crumbs": "middle aisles",
  "gluten-free flour": "middle aisles",
  "rolled oats": "middle aisles",
  "quinoa flour": "middle aisles",
  "almond flour": "middle aisles",
  "coconut flour": "middle aisles",
  "semolina flour": "middle aisles",
  "whole wheat flour": "middle aisles",
  "self-rising flour": "middle aisles",
  "pastry flour": "middle aisles",
  "ap flour": "middle aisles",
  "chocolate chips": "middle aisles",
  oats: "middle aisles",
  "steel-cut oats": "middle aisles",
  "quick oats": "middle aisles",
  polenta: "middle aisles",
  "vanilla extract": "middle aisles",
  "vanilla beans": "middle aisles",
  "vanilla bean": "middle aisles",
  //spices begin
  mace: "middle aisles",
  "garam masala": "middle aisles",
  "sea salt": "middle aisles",
  "iodized salt": "middle aisles",
  salt: "middle aisles",
  "kosher salt": "middle aisles",
  "dried basil": "middle aisles",
  "dried oregano": "middle aisles",
  "dried thyme": "middle aisles",
  "dried rosemary": "middle aisles",
  "dried sage": "middle aisles",
  "dried parsley": "middle aisles",
  "dried cilantro": "middle aisles",
  "dried dill": "middle aisles",
  "dried mint": "middle aisles",
  "bay leaves": "middle aisles",
  "bay leaf": "middle aisles",
  "celery seeds": "middle aisles",
  "celery seed": "middle aisles",
  "file powder": "middle aisles",
  cumin: "middle aisles",
  "cumin (optional)": "middle aisles",
  "ground cumin": "middle aisles",
  paprika: "middle aisles",
  turmeric: "middle aisles",
  "ground turmeric": "middle aisles",
  cinnamon: "middle aisles",
  "cinnamon stick": "middle aisles",
  "cinnamon sticks": "middle aisles",
  nutmeg: "middle aisles",
  ginger: "middle aisles",
  cloves: "middle aisles",
  "whole cloves": "middle aisles",
  "ground cloves": "middle aisles",
  "ground clove": "middle aisles",
  cardamom: "middle aisles",
  "ground cardamom": "middle aisles",
  "cardamom pod": "middle aisles",
  "cardamom pods": "middle aisles",
  coriander: "middle aisles",
  "mustard seeds": "middle aisles",
  fenugreek: "middle aisles",
  "star anise": "middle aisles",
  "whole star anise": "middle aisles",
  "ground star anise": "middle aisles",
  "fennel seeds": "middle aisles",
  "caraway seeds": "middle aisles",
  "pumpkin seeds": "middle aisles",
  "sesame seeds": "middle aisles",
  "chili flakes": "middle aisles",
  "guajillo chili": "middle aisles",
  "chili powder": "middle aisles",
  "curry powder": "middle aisles",
  "dried marjoram": "middle aisles",
  "dried tarragon": "middle aisles",
  "dried chives": "middle aisles",
  saffron: "middle aisles",
  "anise seeds": "middle aisles",
  allspice: "middle aisles",
  "juniper berries": "middle aisles",
  "dried lavender": "middle aisles",
  "onion powder": "middle aisles",
  "garlic powder": "middle aisles",
  "red pepper flakes": "middle aisles",
  "crushed red pepper flakes": "middle aisles",
  "white pepper": "middle aisles",
  "black pepper": "middle aisles",
  pepper: "middle aisles",
  "black peppercorns": "middle aisles",
  "italian seasoning": "middle aisles",
  "herbs de provence": "middle aisles",
  "parchment paper": "middle aisles",
  "olive oil": "middle aisles",
  oil: "middle aisles",
  "balsamic vinegar": "middle aisles",
  "apple cider vinegar": "middle aisles",
  "red wine vinegar": "middle aisles",
  "white wine vinegar": "middle aisles",
  "white vinegar": "middle aisles",
  "coconut vinegar": "middle aisles",
  "sherry vinegar": "middle aisles",
  "distilled vinegar": "middle aisles",
  mirin: "middle aisles",
  tahini: "middle aisles",
  "sesame paste": "middle aisles",
  "tamari sauce": "middle aisles",
  "wasabi paste": "middle aisles",
  "teriyaki sauce": "middle aisles",
  honey: "middle aisles",
  "agave syrup": "middle aisles",
  "maple syrup": "middle aisles",
  molasses: "middle aisles",
  "corn syrup": "middle aisles",
  "vegetable oil": "middle aisles",
  "canola oil": "middle aisles",
  "coconut oil": "middle aisles",
  "avocado oil": "middle aisles",
  "sunflower oil": "middle aisles",
  "peanut oil": "middle aisles",
  "grape seed oil": "middle aisles",
  "corn oil": "middle aisles",
  "soybean oil": "middle aisles",
  "walnut oil": "middle aisles",
  "flaxseed oil": "middle aisles",
  "hempseed oil": "middle aisles",
  "safflower oil": "middle aisles",
  "palm oil": "middle aisles",
  "pumpkin seed oil": "middle aisles",
  "sesame seed oil": "middle aisles",
  "truffle oil": "middle aisles",
  "extra virgin olive oil": "middle aisles",
  peanuts: "middle aisles",
  "peanut butter": "middle aisles",
  almonds: "middle aisles",
  cashews: "middle aisles",
  walnuts: "middle aisles",
  pecans: "middle aisles",
  hazelnuts: "middle aisles",
  pistachios: "middle aisles",
  "macadamia nuts": "middle aisles",
  "brazil nuts": "middle aisles",
  "pine nuts": "middle aisles",
  chestnuts: "middle aisles",
  "almond butter": "middle aisles",
  "cashew butter": "middle aisles",
  "walnut butter": "middle aisles",
  "pecan butter": "middle aisles",
  "hazelnut butter": "middle aisles",
  "pistachio butter": "middle aisles",
  nutella: "middle aisles",
  "achiote paste": "middle aisles",
  "dry sherry": "middle aisles",
  "dry white wine": "middle aisles",
  "evaporated milk": "middle aisles",
};
