export const produceItems = {
  apples: "produce",
  bananas: "produce",
  oranges: "produce",
  tomatoes: "produce",
  "cherry tomatoes": "produce",
  tamatillos: "produce",
  tamatillo: "produce",
  cucumbers: "produce",
  lettuce: "produce",
  "romaine lettuce": "produce",
  "head of lettuce": "produce",
  "lettuce leaves": "produce",
  "lettuce leaf": "produce",
  "hierba santa leaves": "produce",
  carrots: "produce",
  broccoli: "produce",
  strawberries: "produce",
  grapes: "produce",
  blueberries: "produce",
  pineapple: "produce",
  watermelon: "produce",
  peaches: "produce",
  plums: "produce",
  kiwi: "produce",
  spinach: "produce",
  "bell peppers": "produce",
  "red/green pepper": "produce",
  onions: "produce",
  "large onion": "produce",
  "onion (small)": "produce",
  onion: "produce",
  potatoes: "produce",
  avocado: "produce",
  cauliflower: "produce",
  celery: "produce",
  "celery stalks": "produce",
  zucchini: "produce",
  radishes: "produce",
  "green beans": "produce",
  "bean sprouts": "produce",
  asparagus: "produce",
  eggplant: "produce",
  mango: "produce",
  pears: "produce",
  raspberries: "produce",
  blackberries: "produce",
  lemons: "produce",
  lemon: "produce",
  "lemon juice": "produce",
  limes: "produce",
  "lime juice": "produce",
  lime: "produce",
  papaya: "produce",
  cantaloupe: "produce",
  honeydew: "produce",
  apricots: "produce",
  cherries: "produce",
  "brussels sprouts": "produce",
  corn: "produce",
  garlic: "produce",
  "garlic clove": "produce",
  "garlic cloves": "produce",
  "fresh garlic": "produce",
  ginger: "produce",
  "fresh ginger": "produce",
  artichokes: "produce",
  cranberries: "produce",
  pomegranate: "produce",
  dates: "produce",
  lychee: "produce",
  persimmons: "produce",
  "green onions": "produce",
  "red pepper": "produce",
  "green pepper": "produce",
  "red bell pepper": "produce",
  "green bell pepper": "produce",
  jalapenos: "produce",
  "jalapeno peppers": "produce",
  "anaheim peppers": "produce",
  "anaheim pepper": "produce",
  "green chili": "produce",
  "green chilis": "produce",
  "serrano pepper": "produce",
  "serrano peppers": "produce",
  "aji peppers": "produce",
  basil: "produce",
  cilantro: "produce",
  parsley: "produce",
  rosemary: "produce",
  thyme: "produce",
  sage: "produce",
  dill: "produce",
  mint: "produce",
  chives: "produce",
  "fresh chives": "produce",
  "fresh basil": "produce",
  "fresh cilantro": "produce",
  "fresh parsley": "produce",
  "fresh rosemary": "produce",
  "fresh thyme": "produce",
  "fresh sage": "produce",
  "fresh dill": "produce",
  "fresh mint": "produce",
  cabbage: "produce",
  "baby potatoes": "produce",
  "fingerling potatoes": "produce",
  "russet potatoes": "produce",
  "red potatoes": "produce",
  "gold potatoes": "produce",
  "yukon gold potatoes": "produce",
  "yellow potatoes": "produce",
  "white mushrooms": "produce",
  "button mushrooms": "produce",
  "cremini mushrooms": "produce",
  "portobello mushrooms": "produce",
  "shiitake mushrooms": "produce",
  "oyster mushrooms": "produce",
  "maitake mushrooms": "produce",
  "enoki mushrooms": "produce",
  "porcini mushrooms": "produce",
  "morel mushrooms": "produce",
  "chanterelle mushrooms": "produce",
  "lion's mane mushrooms": "produce",
  "hen-of-the-woods mushrooms": "produce",
  "wood ear mushrooms": "produce",
  "nameko mushrooms": "produce",
  "trumpet mushrooms": "produce",
  "beech mushrooms": "produce",
  "pioppino mushrooms": "produce",
  "mushroom medley": "produce",
  "matsutake mushrooms": "produce",
  "coral mushrooms": "produce",
  "chaga mushrooms": "produce",
  "reishi mushrooms": "produce",
  "mushroom blend": "produce",
  "portabella mushrooms": "produce",
  "black trumpet mushrooms": "produce",
  "lobster mushrooms": "produce",
  "king oyster mushrooms": "produce",
  "abalone mushrooms": "produce",
  "shimeji mushrooms": "produce",
  "oyster mushroom clusters": "produce",
  "golden enoki mushrooms": "produce",
  "white beech mushrooms": "produce",
  "yellow oyster mushrooms": "produce",
  "pink oyster mushrooms": "produce",
  "blue oyster mushrooms": "produce",
  "elm oyster mushrooms": "produce",
  "velvet foot mushrooms": "produce",
  "pholiota mushrooms": "produce",
  "hedgehog mushrooms": "produce",
  "shaggy mane mushrooms": "produce",
  "scarlet waxcap mushrooms": "produce",
  "meadow mushrooms": "produce",
  "cloud ear mushrooms": "produce",
  "maitake hen-of-the-woods mushrooms": "produce",
  "yellow bolete mushrooms": "produce",
  "king bolete mushrooms": "produce",
  "bear's head mushrooms": "produce",
  "sheep polypore mushrooms": "produce",
  "puffball mushrooms": "produce",
  "pink bottom mushrooms": "produce",
  "black truffle mushrooms": "produce",
  "white truffle mushrooms": "produce",
  "burgundy truffle mushrooms": "produce",
  "summer truffle mushrooms": "produce",
  "winter truffle mushrooms": "produce",
};
