export const produceItems = {
  apples: "produce",
  bananas: "produce",
  oranges: "produce",
  tomatoes: "produce",
  tamatillos: "produce",
  tamatillo: "produce",
  cucumbers: "produce",
  lettuce: "produce",
  "romaine lettuce": "produce",
  "head of lettuce": "produce",
  "lettuce leaves": "produce",
  "lettuce leaf": "produce",
  "hierba santa leaves": "produce",
  carrots: "produce",
  broccoli: "produce",
  strawberries: "produce",
  grapes: "produce",
  blueberries: "produce",
  pineapple: "produce",
  watermelon: "produce",
  peaches: "produce",
  plums: "produce",
  kiwi: "produce",
  spinach: "produce",
  "bell peppers": "produce",
  "red/green pepper": "produce",
  onions: "produce",
  onion: "produce",
  potatoes: "produce",
  avocado: "produce",
  cauliflower: "produce",
  celery: "produce",
  "celery stalks": "produce",
  zucchini: "produce",
  radishes: "produce",
  "green beans": "produce",
  asparagus: "produce",
  eggplant: "produce",
  mango: "produce",
  pears: "produce",
  raspberries: "produce",
  blackberries: "produce",
  lemons: "produce",
  lemon: "produce",
  "lemon juice": "produce",
  limes: "produce",
  "lime juice": "produce",
  lime: "produce",
  papaya: "produce",
  cantaloupe: "produce",
  honeydew: "produce",
  apricots: "produce",
  cherries: "produce",
  "brussels sprouts": "produce",
  corn: "produce",
  garlic: "produce",
  "garlic cloves": "produce",
  "fresh garlic": "produce",
  ginger: "produce",
  "fresh ginger": "produce",
  artichokes: "produce",
  cranberries: "produce",
  pomegranate: "produce",
  dates: "produce",
  lychee: "produce",
  persimmons: "produce",
  "green onions": "produce",
  "red pepper": "produce",
  "green pepper": "produce",
  "red bell pepper": "produce",
  "green bell pepper": "produce",
  "green chili": "produce",
  "green chilis": "produce",
  "serrano pepper": "produce",
  "serrano peppers": "produce",
  basil: "produce",
  cilantro: "produce",
  parsley: "produce",
  rosemary: "produce",
  thyme: "produce",
  sage: "produce",
  dill: "produce",
  mint: "produce",
  "fresh basil": "produce",
  "fresh cilantro": "produce",
  "fresh parsley": "produce",
  "fresh rosemary": "produce",
  "fresh thyme": "produce",
  "fresh sage": "produce",
  "fresh dill": "produce",
  "fresh mint": "produce",
  cabbage: "produce",
  "russet potatoes": "produce",
  "red potatoes": "produce",
  "gold potatoes": "produce",
  "yukon gold potatoes": "produce",
};
