PUT http://localhost:3001/api/myGroceryList/64a18f519eea4b594cda8ceb
Content-Type: application/json

{
  "name":"ashton bennett",
  "userRecipes": [],
  "userGroceryList": [{"somthing":"somewhere"}],
  "userMenus": [],
     "userStapleIngredients": {
    "itemsToNeverAdd": ["Should be an ingredient obj here"],
    "quickAddItems": ["Should be an ingredient obj here"]
  }
  }

